let readyForClick = true;

function invokeMap(mapId) {
    /* 
    0 = -1 pietro
    1 = 0 pietro
    2 = 1 pietro
    3 = 2 pietro
    4 = drugi budynek
    */
    let maps = [
        `<!-- Image Map Generated by http://www.image-map.net/ -->
        <img src="images/mapa sali -1 (1).png" usemap="#image-map">

        <map name="image-map">
            <area target="" alt="01" title="01" onClick="mapHandler('01')" coords="145,398,271,528" shape="rect">
            <area target="" alt="bufet" title="bufet" onClick="mapHandler('bufet')" coords="324,403,696,527" shape="rect">
            <area target="" alt="szatnia1" title="szatnia1" onClick="mapHandler('szatnia')" coords="700,398,826,526" shape="rect">
            <area target="" alt="036" title="036" onClick="mapHandler('036')" coords="829,398,955,527" shape="rect">
            <area target="" alt="037" title="037" onClick="mapHandler('037')" coords="958,401,1082,524" shape="rect">
            <area target="" alt="szatnia2" title="szatnia2" onClick="mapHandler('szatnia')" coords="1086,404,1283,527" shape="rect">
            <area target="" alt="schody1" title="schody0" onClick="mapHandler('schody1')" coords="247,644,341,699" shape="rect">
            <area target="" alt="schody2" title="schody1" onClick="mapHandler('schody2')" coords="1122,575,1211,637" shape="rect">
            <area target="" alt="wc" title="wc" onClick="mapHandler('wc')" coords="1117,640,1216,721" shape="rect">
        </map>`,
        `<!-- Image Map Generated by http://www.image-map.net/ -->
        <img src="images/mapa sali 0.png" usemap="#image-map">

        <map name="image-map">
            <area target="" alt="24" title="24" onClick="mapHandler('24')" coords="23,537,194,660" shape="rect">
            <area target="" alt="23" title="23" onClick="mapHandler('23')" coords="196,538,310,660" shape="rect">
            <area target="" alt="22" title="22" onClick="mapHandler('22')" coords="313,538,491,660" shape="rect">
            <area target="" alt="21" title="21" onClick="mapHandler('21')" coords="494,537,671,658" shape="rect">
            <area target="" alt="20" title="20" onClick="mapHandler('20')" coords="673,538,836,664" shape="rect">
            <area target="" alt="19" title="19" onClick="mapHandler('19')" coords="837,535,996,661" shape="rect">
            <area target="" alt="18" title="18" onClick="mapHandler('18')" coords="996,380,1095,470" shape="rect">
            <area target="" alt="szatnie" title="szatnie" onClick="mapHandler('szatnia')" coords="999,138,1096,376" shape="rect">
            <area target="" alt="sala gim" title="sala gim" onClick="mapHandler('sala gim')" coords="1161,168,1332,389" shape="rect">
            <area target="" alt="16" title="16" onClick="mapHandler('16')" coords="1191,390,1243,468" shape="rect">
            <area target="" alt="15" title="15" onClick="mapHandler('15')" coords="1245,391,1334,487" shape="rect">
            <area target="" alt="12/13" title="12/13" onClick="mapHandler('12/13')" coords="1196,514,1336,550" shape="rect">
            <area target="" alt="14" title="14" onClick="mapHandler('14')" coords="1270,489,1332,513" shape="rect">
            <area target="" alt="10" title="10" onClick="mapHandler('10')" coords="1256,552,1462,704" shape="rect">
            <area target="" alt="pokoj adm" title="pokoj adm" onClick="mapHandler('pokoj adm')" coords="1213,746,1510,855" shape="rect">
            <area target="" alt="schody1" title="schody1" onClick="mapHandler('schody3')" coords="994,712,1088,770" shape="rect">
            <area target="" alt="schody2" title="schody2" onClick="mapHandler('schody4')" coords="121,780,214,838" shape="rect">
        <area target="" alt="wc" title="wc" onClick="mapHandler('wc')" coords="996,776,1086,853" shape="rect">
        </map>`,
        `<!-- Image Map Generated by http://www.image-map.net/ -->
        <img src="images/mapa sali 1.png" usemap="#image-map">

        <map name="image-map">
            <area target="" alt="101" title="101" onClick="mapHandler('101')" coords="20,537,197,660" shape="rect">
            <area target="" alt="102a" title="102a" onClick="mapHandler('102a')" coords="197,538,314,660" shape="rect">
            <area target="" alt="102b" title="102b" onClick="mapHandler('102b')" coords="313,538,490,661" shape="rect">
            <area target="" alt="103" title="103" onClick="mapHandler('103')" coords="493,537,628,661" shape="rect">
            <area target="" alt="szatnia" title="szatnia" onClick="mapHandler('szatnia')" coords="631,537,671,663" shape="rect">
            <area target="" alt="104" title="104" onClick="mapHandler('104')" coords="672,538,836,661" shape="rect">
            <area target="" alt="105" title="105" onClick="mapHandler('105')" coords="839,541,997,657" shape="rect">
            <area target="" alt="106" title="106" onClick="mapHandler('106')" coords="1000,538,1198,660" shape="rect">
            <area target="" alt="107" title="107" onClick="mapHandler('107')" coords="1202,557,1329,698" shape="rect">
            <area target="" alt="108" title="108" onClick="mapHandler('108')" coords="1335,552,1464,697" shape="rect">
            <area target="" alt="109" title="109" onClick="mapHandler('109')" coords="1464,551,1557,742" shape="rect">
            <area target="" alt="110a" title="110a" onClick="mapHandler('110a')" coords="1425,746,1512,855" shape="rect">
            <area target="" alt="pokoj naucz" title="pokoj naucz" onClick="mapHandler('pokoj naucz')" coords="1308,745,1424,855" shape="rect">
            <area target="" alt="111" title="111" onClick="mapHandler('111')" coords="1213,743,1307,856" shape="rect">
            <area target="" alt="schody1" title="schody1" onClick="mapHandler('schody5')" coords="994,712,1088,773" shape="rect">
            <area target="" alt="wc" title="wc" onClick="mapHandler('wc')" coords="993,776,1088,856" shape="rect">
            <area target="" alt="schody2" title="schody2" onClick="mapHandler('schody6')" coords="122,777,216,839" shape="rect">
        </map>`,
        `<!-- Image Map Generated by http://www.image-map.net/ -->
        <img src="images/mapa sali 2.png" usemap="#image-map">

        <map name="image-map">
            <area target="" alt="201" title="201" onClick="mapHandler('201')" coords="20,538,247,660" shape="rect">
            <area target="" alt="202" title="202" onClick="mapHandler('202')" coords="249,538,463,663" shape="rect">
            <area target="" alt="203" title="203" onClick="mapHandler('203')" coords="463,535,673,663" shape="rect">
            <area target="" alt="204" title="204" onClick="mapHandler('204')" coords="675,535,839,660" shape="rect">
            <area target="" alt="205" title="205" onClick="mapHandler('205')" coords="839,534,993,664" shape="rect">
            <area target="" alt="206" title="206" onClick="mapHandler('206')" coords="999,537,1196,660" shape="rect">
            <area target="" alt="207" title="207" onClick="mapHandler('207')" coords="1199,550,1334,698" shape="rect">
            <area target="" alt="208" title="208" onClick="mapHandler('208')" coords="1338,552,1464,699" shape="rect">
            <area target="" alt="209" title="209" onClick="mapHandler('209')" coords="1469,551,1557,745" shape="rect">
            <area target="" alt="210" title="210" onClick="mapHandler('210')" coords="1373,746,1509,860" shape="rect">
            <area target="" alt="211" title="211" onClick="mapHandler('211')" coords="1215,746,1372,851" shape="rect">
            <area target="" alt="schody1" title="schody1" onClick="mapHandler('schody7')" coords="993,714,1085,773" shape="rect">
            <area target="" alt="wc" title="wc" onClick="mapHandler('wc')" coords="996,773,1088,855" shape="rect">
            <area target="" alt="schody2" title="schody2" onClick="mapHandler('schody8')" coords="127,778,214,839" shape="rect">
        </map>`,
        `<!-- Image Map Generated by http://www.image-map.net/ -->
<img src="mapa sali 2 budynek poprawione.png" usemap="#image-map">

<map name="image-map">
    <area target="" alt="szatnia" title="szatnia" onClick="mapHandler('szatnia')" coords="1287,591,1589,694" shape="rect">
    <area target="" alt="wc" title="wc" onClick="mapHandler('wc')" coords="734,774,970,868" shape="rect">
    <area target="" alt="szatniawf" title="szatniawf" onClick="mapHandler('szatniawf')" coords="131,773,357,870" shape="rect">
    <area target="" alt="silownia" title="silownia" onClick="mapHandler('silownia')" coords="411,451,493,448,497,698,201,695,201,644,405,643" shape="poly">
    <area target="" alt="012" title="012" onClick="mapHandler('012')" coords="35,184,132,322" shape="rect">
    <area target="" alt="12a" title="12a" onClick="mapHandler('12a')" coords="37,325,131,480" shape="rect">
    <area target="" alt="011/010" title="011/010" onClick="mapHandler('011/010')" coords="39,485,131,620" shape="rect">
    <area target="" alt="09a" title="09a" onClick="mapHandler('09a')" coords="40,622,131,749" shape="rect">
    <area target="" alt="09" title="09" onClick="mapHandler('09')" coords="39,752,129,870" shape="rect">
    <area target="" alt="06" title="06" onClick="mapHandler('06')" coords="357,771,435,869" shape="rect">
    <area target="" alt="05" title="05" onClick="mapHandler('05')" coords="436,814,494,870" shape="rect">
    <area target="" alt="04" title="04" onClick="mapHandler('04')" coords="586,771,731,865" shape="rect">
    <area target="" alt="02" title="02" onClick="mapHandler('02')" coords="972,776,1143,870" shape="rect">
    <area target="" alt="02a" title="02a" onClick="mapHandler('02a')" coords="1146,777,1239,869" shape="rect">
    <area target="" alt="013" title="013" onClick="mapHandler('013')" coords="199,449,409,641" shape="rect">
    <area target="" alt="014" title="014" onClick="mapHandler('014')" coords="200,117,307,448" shape="rect">
    <area target="" alt="015" title="015" onClick="mapHandler('015')" coords="309,119,419,449" shape="rect">
    <area target="" alt="016" title="016" onClick="mapHandler('016')" coords="420,122,586,401" shape="rect">
    <area target="" alt="018" title="018" onClick="mapHandler('018')" coords="587,120,695,448" shape="rect">
    <area target="" alt="021" title="021" onClick="mapHandler('021')" coords="586,451,748,692" shape="rect">
    <area target="" alt="022" title="022" onClick="mapHandler('022')" coords="696,122,808,449" shape="rect">
    <area target="" alt="scem" title="scem" onClick="mapHandler('scem')" coords="809,122,1024,451" shape="rect">
    <area target="" alt="025" title="025" onClick="mapHandler('025')" coords="852,452,1023,527" shape="rect">
    <area target="" alt="026" title="026" onClick="mapHandler('026')" coords="805,527,1023,698" shape="rect">
    <area target="" alt="030" title="030" onClick="mapHandler('030')" coords="1027,119,1245,451" shape="rect">
    <area target="" alt="028" title="028" onClick="mapHandler('028')" coords="1027,451,1140,697" shape="rect">
    <area target="" alt="029" title="029" onClick="mapHandler('029')" coords="1141,449,1247,695" shape="rect">
</map>`,
    ]
    document.getElementById("game_window").innerHTML = maps[mapId];
    imageMapResize();
}

function invokeRoom(roomId) {
    let rooms = [];
    document.getElementById("game_window").innerHTML = rooms[roomId];
    imageMapResize();
}

function popUp(text, time = 2000) {
    document.getElementById("game_window").innerHTML += `<div class="popup"></div>`;
    fitTextToContainer(document.querySelector(`div[class="popup"]`), text, 200);
    readyForClick = false;
    setTimeout(() => {
        document.getElementsByClassName("popup")[0].remove();
        readyForClick = true;
    }, time);
}

async function startTeacherInteraction(teacherId) {
    let teacher = getTeacher(teacherId);
    await teacher.loadDialogDOM();
    await teacher.quiz(0);
}

function stairMenu(stairId) {
    function close() {
        readyForClick = true;
        document.querySelector('div[class="popup"]').remove()
        document.querySelector('div[class="stairMenu"]').remove()
    }
    function up() {
        close()
        if (stairId == "schody1" || stairId == "schody2") {
            invokeMap(1);
        } else if (stairId == "schody3" || stairId == "schody4") {
            invokeMap(2);
        } else if (stairId == "schody5" || stairId == "schody6") {
            invokeMap(3);
        } else if (stairId == "schody7" || stairId == "schody8") {
            popUp("Zabawne. Nie jesteś duchem i nie przenikniesz na wyższe piętro. Zabieram ci za to ture");
            nextPlayer();
        } else {
            popUp("Nie ma takich schodów... (Nie klikaj w to więcej prosze :3)");
        }
    }
    function down() {
        close();
        if (stairId == "schody1" || stairId == "schody2") {
            popUp("Zabawne. Nie jesteś duchem i nie przenikniesz na niższe piętro. Zabieram ci za to ture");
            nextPlayer();
        } else if (stairId == "schody3" || stairId == "schody4") {
            invokeMap(0);
        } else if (stairId == "schody5" || stairId == "schody6") {
            invokeMap(1);
        } else if (stairId == "schody7" || stairId == "schody8") {
            invokeMap(2);
        } else {
            popUp("Nie ma takich schodów... (Nie klikaj w to więcej prosze :3)");
        }
    }
    readyForClick = false;
    document.getElementById("game_window").innerHTML += `<div class="popup">W góre czy w dół?</div>`;
    document.getElementById("game_window").innerHTML += `<div class="stairMenu">
                    <section class="stairMenuSection" id="stairUp">W góre</section>
                    <section class="stairMenuSection" id="stairDown">W dół</section>
                    <section class="stairMenuSection" id="cancel">Anuluj</section></div>`;
    document.getElementById('stairUp').addEventListener('click', () => up());
    document.getElementById('stairDown').addEventListener('click', () => down());
    document.getElementById('cancel').addEventListener('click', () => close());
}

async function mapHandler(id) {
    if (!readyForClick) return;

    switch (id) {
        case "wc": {
            popUp("Toaleta jest nieczynna");
            break;
        }
        case "szatnia": {
            popUp("Zapomniałeś identyfikatora do szatni");
            break;
        }
        case "szatniawf": {
            popUp("Nie masz klucza do szatni");
            break;
        }
        case "silownia": {
            popUp("Silownia jest chwilowo niedostępna");
            break;
        }
        case "scem": {
            popUp("SCEM chwilowo zamkniety");
            break;
        }

        case "pokojnauczycielski": {
            popUp("Nie jesteś nauczycielem");
            break;
        }
        case "pokoj adm": {
            popUp("Nie chcesz tam trafić");
            break;
        }
        case "schody1": {
            stairMenu("schody1");
            break;
        }
        case "schody2": {
            stairMenu("schody2");
            break;
        }
        case "schody3": {
            stairMenu("schody3");
            break;
        }
        case "schody4": {
            stairMenu("schody4");
            break;
        }
        case "schody5": {
            stairMenu("schody5");
            break;
        }
        case "schody6": {
            stairMenu("schody6");
            break;
        }
        case "schody7": {
            stairMenu("schody7");
            break;
        }
        case "schody8": {
            stairMenu("schody8");
            break;
        }
        case "101": {
            await startTeacherInteraction("matura_matematyka");
            break;
        }
        case "036": {
            await startTeacherInteraction("matura_matematyka");
            break;
        }
        case "24": {
            await startTeacherInteraction("matura_matematyka");
            break;
        }
        case "22": {
            await startTeacherInteraction("matura_matematyka");
            break;
        }
        case "20": {
            await startTeacherInteraction("matura_matematyka");
            break;
        }
        case "18": {
            await startTeacherInteraction("matura_matematyka");
            break;
        }
        case "15": {
            await startTeacherInteraction("matura_matematyka");
            break;
        }
        case "14": {
            await startTeacherInteraction("matura_matematyka");
            break;
        }
        case "102a": {
            await startTeacherInteraction("matura_matematyka");
            break;
        }
        case "103": {
            await startTeacherInteraction("matura_matematyka");
            break;
        }
        case "105": {
            await startTeacherInteraction("matura_matematyka");
            break;
        }
        case "107": {
            await startTeacherInteraction("matura_matematyka");
            break;
        }
        case "109": {
            await startTeacherInteraction("matura_matematyka");
            break;
        }
        case "111": {
            await startTeacherInteraction("matura_matematyka");
            break;
        }
        case "202": {
            await startTeacherInteraction("matura_matematyka");
            break;
        }
        case "204": {
            await startTeacherInteraction("matura_matematyka");
            break;
        }
        case "206": {
            await startTeacherInteraction("matura_matematyka");
            break;
        }
        case "208": {
            await startTeacherInteraction("matura_matematyka");
            break;
        }
        case "210": {
            await startTeacherInteraction("matura_matematyka");
            break;
        }
        case "01": {
            popUp("W sali nie ma nauczyciela");
            break;
        }
        case "037": {
            popUp("W sali nie ma nauczyciela");
            break;
        }
        case "23": {
            popUp("W sali nie ma nauczyciela");
            break;
        }
        case "21": {
            popUp("W sali nie ma nauczyciela");
            break;
        }
        case "19": {
            popUp("W sali nie ma nauczyciela");
            break;
        }
        case "16": {
            popUp("W sali nie ma nauczyciela");
            break;
        }
        case "12/13": {
            popUp("W sali nie ma nauczyciela");
            break;
        }
        case "10": {
            popUp("W sali nie ma nauczyciela");
            break;
        }
        case "102b": {
            popUp("W sali nie ma nauczyciela");
            break;
        }
        case "104": {
            popUp("W sali nie ma nauczyciela");
            break;
        }
        case "106": {
            popUp("W sali nie ma nauczyciela");
            break;
        }
        case "108": {
            popUp("W sali nie ma nauczyciela");
            break;
        }
        case "110a": {
            popUp("W sali nie ma nauczyciela");
            break;
        }
        case "201": {
            popUp("W sali nie ma nauczyciela");
            break;
        }
        case "203": {
            popUp("W sali nie ma nauczyciela");
            break;
        }
        case "205": {
            popUp("W sali nie ma nauczyciela");
            break;
        }
        case "207": {
            popUp("W sali nie ma nauczyciela");
            break;
        }
        case "209": {
            popUp("W sali nie ma nauczyciela");
            break;
        }
        case "211": {
            popUp("W sali nie ma nauczyciela");
            break;
        }

        default: {
            console.error("Nieprawidłowy identyfikator: ", id);
            break;
        }
    }
}