class player{
    constructor(name, year){
        this.name = name;
        this.year = year;
        this.quizesDone = [];
        this.currentRoom;
        this.sprite = "";
    }
}
/*
<!-- Image Map Generated by http://www.image-map.net/ -->
<img src="mapa sali 1.png" usemap="#image-map">

<map name="image-map">
    <area target="" alt="101" title="101" href="" coords="27,540,195,661" shape="rect">
    <area target="" alt="102a" title="102a" href="" coords="201,540,310,661" shape="rect">
    <area target="" alt="102b" title="102b" href="" coords="315,540,488,660" shape="rect">
    <area target="" alt="103" title="103" href="" coords="495,540,625,661" shape="rect">
    <area target="" alt="104" title="104" href="" coords="834,660,674,540" shape="rect">
    <area target="" alt="105" title="105" href="" coords="840,541,994,658" shape="rect">
    <area target="" alt="106" title="106" href="" coords="998,540,1192,658" shape="rect">
    <area target="" alt="107" title="107" href="" coords="1201,555,1327,694" shape="rect">
    <area target="" alt="108" title="108" href="" coords="1336,554,1459,695" shape="rect">
    <area target="" alt="109" title="109" href="" coords="1467,555,1553,743" shape="rect">
    <area target="" alt="111" title="111" href="" coords="1303,853,1220,747" shape="rect">
    <area target="" alt="stairs" title="stairs" href="" coords="1081,771,1002,718" shape="rect">
    <area target="" alt="szatnia" title="szatnia" href="" coords="633,541,667,660" shape="rect">
    <area target="" alt="pokojnauczycielski" title="pokojnauczycielski" href="" coords="1312,750,1423,853" shape="rect">
    <area target="" alt="110a" title="110a" href="" coords="1426,750,1508,852" shape="rect">
    <area target="" alt="WC" title="WC" href="" coords="999,777,1081,855" shape="rect">
</map>
*/