/*
class mapClass{
    constructor(){
        //roomId, [x, y], arrows
        //arrows [[x, y, direction, roomId], ...] (direction: 0 - up, 1 - right, 2 - down, 3 - left)
        self.rooms = [
            ["room0", [20, 20], [[86, 67, 1, 1]]],
            ["room1", [60, 20], [[86, 67, 1, 0]]]
        ];
        self.currentRoom = 0;
        self.playersInRooms = [[0, 1]]; //[playerId, roomId]
    }

    gotoRoom(roomId){
        document.getElementById("room").remove();
        this.viewRoom(roomId);
        for(let i = 0; i < self.playersInRooms.length; i++){
            if(self.playersInRooms[i][1] === roomId){
                this.viewPlayer(self.playersInRooms[i][0]);
            }
        }
        this.addArrows();
    }

    viewRoom(roomId){
        let imgEle = document.createElement("div");
        imgEle.className = self.rooms[roomId][0];
        imgEle.id = "room";
        self.currentRoom = roomId;
        document.getElementById("game_window").appendChild(imgEle);
    }

    viewPlayer(playerId){
        let playerSpriteEle = document.createElement("div");
        playerSpriteEle.className = "player" + playerId;
        let [x, y] = self.rooms[self.currentRoom][1];
        playerSpriteEle.style = `position: absolute; left: ${x}%; top: ${y}%`;
        document.getElementById("room").appendChild(playerSpriteEle);
    }

    addArrows(){
        let arrows = self.rooms[self.currentRoom][2];
        for(let i = 0; i < arrows.length; i++){
            let arrowEle = document.createElement("div");
            arrowEle.className = "arrow";
            let [x, y, direction, roomId] = arrows[i];
            arrowEle.style = `position: absolute; left: calc(70vw * ${x}/100); top: calc(70vh * ${y}/100); transform: rotate(${90 * direction}deg)`;
            arrowEle.onclick = () => {
                this.gotoRoom(roomId);
            };
            document.getElementById("room").appendChild(arrowEle);
        }
    }
}
*/

let readyForClick = true;

function invokeMap(mapId){
    let maps = [`<!-- Image Map Generated by http://www.image-map.net/ -->
    <img src="mapa sali 1.png" usemap="#image-map">

    <map name="image-map">
        <area alt="101" title="101" onclick="mapHandler(0)" coords="27,540,195,661" shape="rect">
        <area alt="102a" title="102a" onclick="mapHandler(1)" coords="201,540,310,661" shape="rect">
        <area alt="102b" title="102b" onclick="mapHandler(2)" coords="315,540,488,660" shape="rect">
        <area alt="103" title="103" onclick="mapHandler(3)" coords="495,540,625,661" shape="rect">
        <area alt="104" title="104" onclick="mapHandler(4)" coords="834,660,674,540" shape="rect">
        <area alt="105" title="105" onclick="mapHandler(5)" coords="840,541,994,658" shape="rect">
        <area alt="106" title="106" onclick="mapHandler(6)" coords="998,540,1192,658" shape="rect">
        <area alt="107" title="107" onclick="mapHandler(7)" coords="1201,555,1327,694" shape="rect">
        <area alt="108" title="108" onclick="mapHandler(8)" coords="1336,554,1459,695" shape="rect">
        <area alt="109" title="109" onclick="mapHandler(9)" coords="1467,555,1553,743" shape="rect">
        <area alt="111" title="111" onclick="mapHandler(10)" coords="1303,853,1220,747" shape="rect">
        <area alt="stairs" title="stairs" onclick="mapHandler(11)" coords="1081,771,1002,718" shape="rect">
        <area alt="szatnia" title="szatnia" onclick="mapHandler('szatnia')" coords="633,541,667,660" shape="rect">
        <area alt="pokojnauczycielski" title="pokojnauczycielski" onclick="mapHandler('pokojnauczycielski')" coords="1312,750,1423,853" shape="rect">
        <area alt="110a" title="110a" onclick="mapHandler(14)" coords="1426,750,1508,852" shape="rect">
        <area alt="WC" title="WC" onclick="mapHandler('wc')" coords="999,777,1081,855" shape="rect">
    </map>`]
    document.getElementById("game_window").innerHTML = maps[mapId];
    imageMapResize();
}

function invokeRoom(roomId){
    let rooms = [];
    document.getElementById("game_window").innerHTML = rooms[roomId];
    imageMapResize();
}

function popUp(text){
    document.getElementById("game_window").innerHTML += `<div class="popup">${text}</div>`;
    readyForClick = false;
    setTimeout(() => {
        document.getElementsByClassName("popup")[0].remove();
        readyForClick = true;
    }, 3000);
}

function mapHandler(id){
    if(!readyForClick) return;
    switch(id){
        case "wc": {
            popUp("Toaleta jest nieczynna");
            break;
        }
        case "szatnia": {
            popUp("Zapomniałeś identyfikatora do szatni");
            break;
        }
        case "pokojnauczycielski": {
            popUp("Nie jesteś nauczycielem");
            break;
        }
        case 0: {
            let teacher = getTeacher(0);
            break;
        }
        default: {
            console.error("Nieprawidłowy identyfikator: ", id);
            break;
        }
    }
}